services:

  management:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: management-service

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./workspace:/workspace
      - ./nginx:/shared-nginx

    networks:
      - proxy-network

    restart: unless-stopped


  nginx:
    image: nginx:alpine

    container_name: onprem-nginx

    ports:
      - "80:80"

    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/snippets:/etc/nginx/snippets:ro

    depends_on:
      - management

    networks:
      - proxy-network

    restart: unless-stopped


networks:

  proxy-network:
    name: proxy-network